version: '3.8'
services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
